module.exports = {
  GIFT_TYPES: {
    MUG: 'MUG', 
    T_SHIRT: 'T_SHIRT', 
    HOODIE: 'HOODIE', 
    STICKER: 'STICKER'
  },
  WORKFLOW_STATUS: {
    ORDER_RECEIVED: 'ORDER_RECEIVED', 
    ORDER_PROCESSING: 'ORDER_PROCESSING', 
    ORDER_SHIPPED: 'ORDER_SHIPPED', 
    ORDER_CANCELLED: 'ORDER_CANCELLED'
  },
  MAX_RECIPIENTS: 20,
  MAX_DAILY_GIFTS: 60
}